import redis
import barch
print("start redis test")
barch.start("0.0.0.0", 14000)
# connect redis client to barch running inside this process
r = redis.Redis(host="127.0.0.0", port=14000, db=0)
r.flushdb()
p = r.pipeline()
p.set('a','va')
p.set('b','vb')
p.set('c','vc')
p.execute()

r.set("hello","barch")
print(r.get("hello"))
print(r.get("hello1"))
print(r.dbsize())
assert(r.get("hello") == b'barch')
assert(r.dbsize() == 4)
r.execute_command("USE src")
r.flushdb()
r.execute_command("SET vkey srcv")
r.execute_command("SET ukey srcu")
print(r.dbsize())
assert(r.dbsize()==2)
r.execute_command("USE deputya")
assert(r.dbsize()==0)
r.execute_command("USE")
assert(r.dbsize()==4)
r.execute_command("USE dep")
r.flushdb()
r.set("a","depa")
r.set("b","depb")
r.set("c","depc")
r.set("d","depd")
assert(r.dbsize()==4)
r.execute_command("USE src")
r.flushdb()
r.set("c","srcc")
r.set("e","srce")
r.set("z","srcz")
assert(r.dbsize()==3)
assert(r.dbsize()-1 == len(r.execute_command("RANGE a z -1")))
r.execute_command("SPACES DEPENDS dep ON src")
r.execute_command("USE dep")
assert(len(r.execute_command("RANGE a z -1"))==5)
assert(r.dbsize()==7)
print(r.get("z"))
assert(r.get("z")==b'srcz')
r.execute_command("REM z")
assert(r.get("z")==None)
print(r.dbsize())
r.execute_command("USE src")
assert(r.get("z")==b'srcz')
assert(3 == r.dbsize())
print("complete redis test")