for cnt in range(1,5):
    import redis
    import barch
    print(f"start redis test {cnt}")
    barch.start("0.0.0.0", 14000)
    # connect redis client to barch running inside this process
    r = redis.Redis(host="127.0.0.0", port=14000, db=0)
    r.execute_command("CLEARALL")
    r.execute_command("SAVEALL")

    p = r.pipeline()
    p.set('a','va')
    p.set('b','vb')
    r.execute_command("pipe:SET a spca")
    p.set('c','vc')
    r.execute_command("pipe:SET a spca")
    p.execute()
    assert(r.execute_command("pipe:GET a") == b'spca')
    print("r.execute_command('GET a')",r.execute_command("GET a"))
    assert(r.execute_command("GET a") == b'va')
    assert(r.execute_command("SPACES EXIST pipe") == 1)

    r.set("hello","barch")
    assert(r.get("hello") == b'barch')
    assert(r.dbsize() == 4)
    r.execute_command("USE src")
    r.flushdb()
    r.execute_command("SET vkey srcv")
    r.execute_command("SET ukey srcu")
    assert(r.dbsize()==2)
    r.execute_command("USE deputya")
    assert(r.dbsize()==0)
    r.execute_command("USE")
    assert(r.dbsize()==4)
    r.execute_command("USE dep")
    r.flushdb()
    r.set("a","depa")
    r.set("b","depb")
    r.set("c","depc")
    r.set("d","depd")
    assert (r.dbsize()>=4)
    print(r.dbsize())
    r.execute_command("USE src")
    r.flushdb()
    r.set("c","srcc")
    r.set("e","srce")
    r.set("z","srcz")
    assert(r.dbsize()==3)
    assert(r.dbsize()-1 == len(r.execute_command("RANGE a z -1")))
    r.execute_command("SPACES DEPENDS dep ON src")
    r.execute_command("USE dep")
    assert(len(r.execute_command("RANGE a z -1"))==5)
    assert(r.dbsize()==7)
    #print(r.get("z"))
    assert(r.get("z")==b'srcz')
    r.execute_command("REM z")
    assert(r.get("z")==None)
    #print(r.dbsize())
    r.execute_command("USE src")
    assert(r.get("z")==b'srcz')
    assert(3 == r.dbsize())

    r.execute_command("mspce:SET a mspce_a")
    assert(r.execute_command("mspce:GET a") == b'mspce_a')
    assert(r.execute_command("SPACES DEPENDS a ON mspce") == b'OK')

    assert(r.execute_command("a:GET a") == b'mspce_a')
    assert(r.execute_command("SPACES DROP a") == b'OK')
    assert(r.execute_command("SPACES DROP mspce") == b'OK')
    assert(r.execute_command("a:GET a") == None)
    assert(r.execute_command("SPACES DROP a") == b'OK')
    r.close()
    barch.stop()
print(f"complete redis test")