import time
import barch
barch.setRoute(0,"127.0.0.1",14500)
barch.clearAll()
barch.saveAll()
print(barch.repl_stats())
print(barch.ops_stats())
print(barch.stats())
print(barch.config())
r = barch.getRoute(0)
assert(r.host.s() == "127.0.0.1")
assert(r.port.i() == 14500)
barch.removeRoute(0)
r = barch.getRoute(0)
assert(r.host.s() == "" and r.port.i()==0)
barch.clear()
s = barch.size()
assert(s == 0)
k = barch.KeyValue()
assert(k.use("test"))
h = barch.HashSet()
k.set("1","one")
k.set("2","two")
k.set("3","three")
assert(k.min().i() == 1)
assert(k.max().i() == 3)
assert(k.upperBound("2").i() == 3 )
assert(k.lowerBound("2").i() == 2)
assert(k.count("2","3") == 1)
assert(k.size()==3)
assert(k.size()<=barch.sizeAll())
assert(k.get("1") == "one")
k.set('one',"1")
k.incr('one',1)
assert(k.get('one') == "2")
k.decr('one',1)
assert(k.get('one') == "1")
k.incr('one', 1.0)
assert(k.get('one') == "2")
k.decr('one',1.0)
assert(k.get('one') == "1")
k.erase('one')
assert not k.exists('one')
k.erase("1")
s = barch.sizeAll()
assert(s == 2)
barch.save()
barch.clearAll()
barch.saveAll()
assert(0 == barch.size())
h.set("k3",["f1","v1","f2","v2"])
assert(h.ttl("k3",["f1"])[0].i() == -1)
s = barch.size()
assert(h.remove("k3", ["f1"]).i() == 1)
assert(s -1 == barch.size())
assert(h.mget("k3",["f2"])[0].t() == 'string')
h.set("kxp",["f1","v1","f2","v2"])
h.expire("kxp",["10", "NX"],["f1","f2"])
assert(h.mget("kxp",["f1","f2"])[0].s() == "v1")
assert(h.ttl("kxp",["f1"])[0].i() >= 9)
s = int(time.time())
assert(h.expireat("kxp",s,"XX",["f1"])[0].i()==1)
h.set("kn",["f1","0","f2","1"])
assert(h.incrby("kn","f1",1).i() == 1)
z = barch.OrderedSet()
assert(z.add("z1",[],["1","one","2","two","3","three"]).i() == 3)
assert(z.range("z1",1.99,3.01,[])[0].s() == "two")
assert(z.range("z1",1.99,3.01,["WITHSCORES"])[1].d() == 2)
assert(z.rank("z1",0, 2).i() == 1)
assert(z.card("z1").i() == 3)

assert(z.add("z2", ["1","one","2","two","5","five"]).i() == 3)
assert(z.diff(["z1","z2"])[0].s()=="three")
assert(z.diff(["z2","z1"])[0].s()=="five")
assert(z.inter(["z2","z1"])[0].s()=="one")
assert(z.intercard(["z2","z1"]).i()==2)
assert(z.diffstore("z1.2",["z1","z2"]).i()==1)
assert(z.diffstore("z2.1",["z2","z1"]).i()==1)
assert(z.card("z2.1").i() == 1)

assert(z.popmin("z1").i() == 1)
assert(z.card("z1").i() == 2)
assert(z.range("z1",1.99,3.01,["WITHSCORES"])[1].d() == 2)
assert(z.popmax("z1").i() == 3)
assert(z.range("z1",1.99,3.01,["WITHSCORES"])[1].d() == 2)
s = barch.size()
assert(z.remove("z1","1").i() == 1)
assert(barch.size() + 1 == s)

assert(z.add("zi", ["1","one","2","two","5","five"]).i() == 3)
s = barch.size()
z.incrby("zi",11,"one")
assert(z.range("zi", 0,10)[0].s()=="two")
assert(z.card("zi").i()==3)
assert(z.range("zi", 10.5, 20)[0].s()=="one")

assert (s==barch.size())
barch.save()
assert(z.remrangebylex("zi", "ona", "ond").s()=="0")
assert(z.remrangebylex("zi", "ona", "onf").s()=="1")
assert(z.remrangebylex("zi", "tw", "two").s()=="1")
assert (s==barch.size()+4)

for i in range(10000):
    k.set(f"z{str(i)}",str(i))
# the range end is not inclusive
r = k.range(f"z1000",f"z1009",11)
assert(len(r)==9)
assert(r[0].s()=="z1000")
assert(r[1].s()=="z1001")
z1 = barch.KeyValue()
z1.use("z1")
z1.set("snippy    ", " ")
z1.set(f"1 a","1a")
z1.set(f"1 b","1b")
z1.set(f"1 c","1c")
z1.set(f"1.1 a","1.1a")
z1.set(f"1.1 b","1.1b")
z1.set(f"1.2 a","1.2a")
z1.set(f"1200.0 a","1200a")
assert z1.get(f"1.1 a") == "1.1a"
assert z1.get(f"1200.0 a") == "1200a"
assert z1.get(f"1.2E3 a") == "1200a"
print(z1.range(f'1.0 a', f'1.11 a')[0].s())
assert(z1.range(f'1.0 a', f'1.11 a')[0].s() == "1.1 a")
conf = barch.KeyValue()
conf.use("configuration")

conf.set("mys.shards", "1")
mys = barch.KeyValue()
mys.use("mys")
mys.set("hello","world")
assert(mys.get("hello") == "world")

conf = barch.KeyValue("configuration")
conf.set("text_data.shards","1")
conf.set("spatial_data.shards","1")
conf.set("counters.ordered","0")
conf.set("counters.shards","1")
assert conf.getOrdered()
txt = barch.KeyValue("text_data")
spc = barch.KeyValue("spatial_data")
spc.set("snippy ", " ")
assert spc.get("snippy ") == " "
spc.set(" snippy 1", " ")
assert spc.get(" snippy 1") == " "
spc.set(" snippy2  ", " ")
assert spc.get(" snippy2  ") == " "
spc.set(" snippy1 ", " ")
assert spc.get(" snippy1 ") == " "
spc.set(" snippy1 2 ", "2")
assert spc.get(" snippy1  2 ") == "2"
assert spc.get(" snippy1 2") == "2"
assert spc.get("snippy1 2") == "2"

assert spc.getShards() == 1
assert txt.getShards() == 1
cnt = barch.KeyValue("counters")
cnt.set("records","0")
counter = cnt.get("records")
assert counter == "0"
cnt.incr("records",1)
assert cnt.get("records") == "1"
assert not cnt.getOrdered()
