from b import barch
s = barch.size()
k = barch.KeyMap()
h = barch.HashSet()
k.set("1","one")
k.set("2","two")
k.set("3","three")
s = barch.size()
assert(s == 3)
barch.save()
barch.clear()
barch.save()
assert(0 == barch.size())
h.set("k3",["f1","v1","f2","v2"])
assert(h.ttl("k3",["f1"])[0].i() == -1)
s = barch.size()
h.remove("k3", ["f1"]).i()
assert(s -1 == barch.size())