import time
from b import barch
barch.clear()
s = barch.size()
k = barch.KeyMap()
h = barch.HashSet()
k.set("1","one")
k.set("2","two")
k.set("3","three")
s = barch.size()
assert(s == 3)
barch.save()
barch.clear()
barch.save()
assert(0 == barch.size())
h.set("k3",["f1","v1","f2","v2"])
assert(h.ttl("k3",["f1"])[0].i() == -1)
s = barch.size()
h.remove("k3", ["f1"]).i()
assert(s -1 == barch.size())
assert(h.mget("k3",["f2"])[0].t() == 'string')
h.set("kxp",["f1","v1","f2","v2"])
h.expire("kxp",["10", "NX"],["f1","f2"])
assert(h.mget("kxp",["f1","f2"])[0].s() == "v1")
assert(h.ttl("kxp",["f1"])[0].i() >= 9)
s = int(time.time())
assert(h.expireat("kxp",s,"XX",["f1"])[0].i()==1)
h.set("kn",["f1","0","f2","1"])
assert(h.incrby("kn","f1",1).i() == 1)
z = barch.OrderedSet()
assert(z.add("z1",[],["1","one","2","two","3","three"]).i() == 3)
assert(z.range("z1",1.99,3.01,[])[0].s() == "two")
assert(z.range("z1",1.99,3.01,["WITHSCORES"])[1].d() == 2)
assert(z.rank("z1",0, 2).i() == 1)
assert(z.card("z1").i() == 3)
assert (z.popmin("z1").i() == 1)
assert(z.card("z1").i() == 2)
assert(z.range("z1",1.99,3.01,["WITHSCORES"])[1].d() == 2)
assert (z.popmax("z1").i() == 3)
assert(z.range("z1",1.99,3.01,["WITHSCORES"])[1].d() == 2)
